# Промисы: обработка ошибок

- `.catch` не обязательно должен быть сразу после ошибки, он может быть далее, после одного или нескольких `.then`.
- `.catch` перехватывает все виды ошибок в промисах: будь то вызов `reject()` или ошибка, брошенная в обработчике при помощи `throw`.

## Неявный try..catch

Вокруг функции промиса и обработчиков находится "невидимый" `try..catch`. Это позволяет выбрасывать исключение прямо в них,
и перехватывать в других `.catch`. Также это позволяет перехватывать "неочевидные" исключения.

```js
new Promise((resolve, reject) => {
  resolve("ок");
}).then((result) => {
  blabla(); // нет такой функции
}).catch(alert); // ReferenceError: blabla is not defined
```

## Необработанные ошибки

Если обработчиков нет, то скрипт "умрет", будто бы промиса и не было.

Можно такие "необработанные" ошибки поймать например так:
```js
window.addEventListener('unhandledrejection', function(event) {
  // объект события имеет два специальных свойства:
  alert(event.promise); // [object Promise] - промис, который сгенерировал ошибку
  alert(event.reason); // Error: Ошибка! - объект ошибки, которая не была обработана
});

new Promise(function() {
  throw new Error("Ошибка!");
}); // нет обработчика ошибок
```
